spring:
  application.name: @project.name@
  threads.virtual.enabled: true

server:
  port: 9000

logging:
  file.name: templates-poc.log
  level:
    com.github.simy4.poc: DEBUG
    com.github.simy4.poc.velocity: WARN
    org.springframework: WARN
    org.apache.velocity: WARN
    freemarker: WARN

management.server.port: 9001

springdoc:
  packages-to-scan: com.github.simy4.poc.controllers
