spring:
  application.name: @project.name@
  threads.virtual.enabled: true
  thymeleaf:
    cache: false
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  resourcse:
    cache:
      period: 0
    static-locations: file:src/main/resources/static/

server:
  port: 9000

logging:
  file.name: templates-poc.log
  level:
    com.github.simy4.poc: DEBUG
    com.github.simy4.poc.velocity: WARN
    org.springframework: WARN
    org.apache.velocity: WARN
    freemarker: WARN

management.server.port: 9001
